name: spunkypixels
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.3225806
title: My brain â€¦ on display
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFF66'
    - '#000000'
    - '#FFFFFF'
    - '#A3ACB8'
    - '#777730'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
